version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Biofuel-API
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: /home/ubuntu/Biofuel-API/scripts/BeforeInstallHook.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: /home/ubuntu/Biofuel-API/scripts/AfterInstallHook.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: /home/ubuntu/Biofuel-API/scripts/Applicationstart.sh
      timeout: 300
      runas: ubuntu