version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Nidhi-Bank-API
    overwrite: true
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstallHook.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstallHook.sh
      timeout: 300
